name: em_recharge

channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterhub=1.5
  - cython
  - numpy
  - scipy
  - matplotlib
  - pandas
  - SimPEG
  - pyproj
  - verde
  - ipykernel
  - ipywidgets
  - ipyleaflet
  - ipympl
  - leafmap
  - dill
  - discretize
  - vtk
  - pip
  - pip:
      - scikit-fmm
      - redivis
      - rasterio
      - python-dotenv
      - curvenote
      - rio-cogeo
      - google-resumable-media
      - emrecharge
